### ISSUE TITLE
Bug in initial SMDR run

### ISSUE THREAD

**Issue by minhdng** [statius/RunningCouplings#2]
Problem encountered running first example in `usage-examples.nb`

<img width="1043" alt="Screen Shot 2020-09-16 at 8 09 24 PM" src="https://user-images.githubusercontent.com/21085760/93407841-b8d50480-f858-11ea-9c34-506df2923519.png">

OS: Mac OS Catalina 10.15.6
Mathematica: 12.1.0.0, Student Edition

**Comment by statius** [comment]
Was this the first evaluation after you loaded the package on a clean kernel?

Also, could you give me the output of 
1. `RunningCouplings["SM", "TopQuarkPoleMassScale"]`? This will test to see if SMDR is working.
2. ``RunningCouplings`Private`betaFunction["SM", "g1", 2]``? I think the problem may have to do with the context in which various symbols are being defined, and this might be evident in how the beta function definitions are imported.

**Comment by minhdng** [comment]
Yes it was loaded in a clean Kernel.

The first time report errors. 

<img width="1072" alt="Screen Shot 2020-09-17 at 9 47 01 PM" src="https://user-images.githubusercontent.com/21085760/93549617-57339980-f92f-11ea-9433-9562ccf14c36.png">


The second run is fine, which indicates forward defined constants/functions. 

<img width="1066" alt="Screen Shot 2020-09-17 at 9 46 13 PM" src="https://user-images.githubusercontent.com/21085760/93549572-3ec37f00-f92f-11ea-997b-a4e5cd783b1c.png">

**Comment by statius** [comment]
This looks like a failure with SMDR. The code generates the file `RunningCouplings/include/SM/smdr-runningcouplings-mt.wl` after the first run of SMDR to speed things up later. Can you post the contents of this file?

**Comment by minhdng** [comment]
Here it is

<img width="1029" alt="Screen Shot 2020-09-18 at 10 24 22 AM" src="https://user-images.githubusercontent.com/21085760/93615616-3d2ea100-f999-11ea-8b07-f5e56f101cc2.png">

**Comment by statius** [comment]
Ok, it looks like that file is storing an unevaluated command. This is a bug: I need to allow the definition of `RunningCouplings`Private`uRunningCouplings` to take a string (such as `"TopQuarkPoleMassScale"`) as a scale specification. 

I suggest that you delete the file `RunningCouplings/include/SM/smdr-runningcouplings-mt.wl` so that it can be regenerated with the correct values after the bugfix.
